// src/types/index.ts

/**
 * Basic airport entity based on API data.
 */
export interface Airport {
  airportCode: string; // e.g., FRA, LHR
  name: string;
  country: string;
  continent: string;
}

/**
 * Raw and calculated metrics representing the operational state.
 * These serve as proxies for our investment engine.
 */
export interface AirportMetrics {
  airportCode: string;
  totalDailyFlights: number; 
  delayedFlightsPercentage: number; // Proxy for infrastructure pressure/congestion
  longHaulPercentage: number; // Proxy for network quality (flights > 6 hours)
  dominantAirlinePercentage: number; // Proxy for revenue risk (dependency on a single airline)
  uniqueDestinations: number; // Proxy for network diversity
}

/**
 * Dynamic weights for the scoring engine, allowing Human-in-the-Loop (HITL) adjustments.
 */
export interface ScoringWeights {
  infrastructurePressure: number; // Default: 0.40 (40%)
  revenueQuality: number;         // Default: 0.35 (35%)
  networkGravity: number;         // Default: 0.25 (25%)
}

/**
 * The final deterministic output generated by the Scoring Engine.
 */
export interface InvestmentScore {
  airport: Airport;
  metrics: AirportMetrics;
  finalScore: number; // Scale of 1-100
  scoreBreakdown: {
    infrastructureScore: number;
    revenueScore: number;
    networkScore: number;
  };
}

/**
 * The strict data payload injected into the AI Agent's context.
 */
export interface AgentContext {
  userQuery: string;
  analyzedAirports: InvestmentScore[];
}