// src/services/guardrailsService.ts

import { InvestmentScore } from '@/types';

export class LLMGuardrailsService {
  /**
   * Post-processing validation layer (Guardrails).
   * Ensures the AI generated response does not hallucinate the deterministic final scores.
   * 
   * @param aiResponse The text string generated by the LLM
   * @param originalScores The exact scores calculated by the deterministic ScoringEngine
   * @returns A boolean indicating if the AI response is safe and factual
   */
  static isResponseSafe(aiResponse: string, originalScores: InvestmentScore[]): boolean {
    console.log('[Guardrails] Validating AI response for hallucinated metrics...');

    for (const scoreObj of originalScores) {
      const airportCode = scoreObj.airport.airportCode;
      const trueScore = scoreObj.finalScore.toString();
      
      // If the AI mentions the airport, it MUST not invent a fake score for it.
      // This is a basic demonstration of factual grounding validation.
      if (aiResponse.includes(airportCode)) {
        // We check if the correct score appears in the text. 
        // In a production app, we would use strict JSON schemas (Structured Output),
        // but this regex/string validation acts as a solid safety net.
        if (!aiResponse.includes(trueScore)) {
          console.error(`[Guardrails Alert] Hallucination detected for ${airportCode}. Expected score: ${trueScore}`);
          return false;
        }
      }
    }

    console.log('[Guardrails] Response passed factual validation.');
    return true;
  }
}